all:
  children:
    dns:
      children:
        dns_main:
          hosts:
            network01:
              ansible_host: 172.16.32.11
        dns_secondary:
          hosts:
            network02:
              ansible_host: 172.16.32.12
