plugin: community.proxmox.proxmox
url: https://172.16.0.25:8006
user: tofu@pve
token_id: tofu-proxmox-token
token_secret: "{{ lookup('community.general.bitwarden_secrets_manager', '2acbcea8-c5ac-409a-b14d-b4ba002904f9').value }}"
validate_certs: false
want_facts: true
want_proxmox_nodes_ansible_host: false

keyed_groups:
  - key: proxmox_tags_parsed
    separator: ""
    prefix: group

groups:
  debian: "'debian' in (proxmox_tags_parsed|list)"
  databases: "'db' in (proxmox_tags_parsed|list)"
  talos: "'talos' in (proxmox_tags_parsed|list)"

compose:
  ansible_host: proxmox_ipconfig0["ip"].split('/')[0] | default(proxmox_net0.ip) | ipaddr('address')